[package]
name = "commit-checker"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1.0", features = ["macros", "io-util", "sync", "rt-multi-thread"] }
lambda_runtime = "0.5.0"
serde_json = "1.0"