version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "commit-checker-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jrc6b0j5v3dc"
s3_prefix = "commit-checker-stack"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
