version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-stack-name"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wdfh0xkos4ex"
s3_prefix = "sam-app"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
