AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CommitChecker:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Architectures:
      - arm64
      Handler: bootstrap
      Runtime: provided.al2
      Timeout: 5
      CodeUri: build/
    Metadata:
      SamResourceId: CommitChecker
Outputs:
  FunctionName:
    Value:
      Ref: CommitChecker
    Description: Name of the Lambda function
