AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Architectures: ["arm64"]
      Handler: bootstrap
      Runtime: provided.al2
      Timeout: 5
      CodeUri: build/

Outputs:
  FunctionName:
    Value: !Ref HelloWorldFunction
    Description: Name of the Lambda function

    aws lambda invoke
    --cli-binary-format raw-in-base64-out \
    --function-name sam-app-HelloWorldFunction-mjdmEI9bYk4Y \
    --payload '{"command": "Say Hi!" }' \
    output.json